name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate README
        uses: muesli/readme-scribe@master
        env:
          # Using PERSONAL_ACCESS_TOKEN instead of GITHUB_TOKEN
          # The recentContributions function requires a personal access token
          # because it needs to access user activity, which is not available to the github-actions bot
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          template: 'README.gtpl'
          writeTo: 'README.md'

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: 'docs: update README.md [skip ci]'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
