name: Update Profile Statistics

on:
  push:
    branches:
      - main
    paths:
      - 'profile/README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update cache-busting parameter
        run: |
          # Calculate week number for cache busting
          WEEK=$(date +%Y-W%V)

          # Update the profile README with new cache-busting parameter
          sed -i "s/username=GerdsenAI-Admin&/username=GerdsenAI-Admin\&cache_bust=$WEEK\&/g" profile/README.md

          # Also update if cache_bust already exists
          sed -i "s/cache_bust=[^&]*&/cache_bust=$WEEK\&/g" profile/README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: 'docs: update profile statistics [skip ci]'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          file_pattern: 'profile/README.md'
